# Generated by Django 5.2.1 on 2025-05-08 14:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('caption', models.TextField(verbose_name='caption')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ad_images', verbose_name='image')),
                ('is_public', models.BooleanField(default=True, verbose_name='is_public')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2025, 5, 8, 14, 6, 20, 736263, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='publisher')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
                'ordering': ('-date_added',),
                'get_latest_by': 'date_added',
            },
        ),
    ]
